AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AmIRytBackend

Resources:

  LinkTotextConverterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api/
      Handler: linkConverter.linkTotext
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LinkToText:
          Type: Api 
          Properties:
            Path: /link
            Method: post
  
  PdfToTextConverterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api/
      Handler: pdfConverter.pdfToText
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        PdfToText:
          Type: Api 
          Properties:
            Path: /pdf
            Method: post
  
  QuestionGeneratorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api/
      Handler: questionGenerator.textToQuestions
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        PdfToText:
          Type: Api 
          Properties:
            Path: /questions
            Method: post
  
Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
